const mongoose = require('mongoose');

const noteSchema = new mongoose.Schema({
    user_id: { type: mongoose.Schema.Types.ObjectId, required: true, ref: 'user' },
    title: { type: String, required: true },
    text: { type: String, required: true },
}, { timestamps: true });//created_at and updated_at fields are automatically generated by setting timestamps:true;
//_id field for a mongodb Document can be used as the id for a ToDo

const Note = mongoose.model('note', noteSchema);

module.exports = Note; 
